### ISSUE TITLE
AttributeError: can't set attribute

### ISSUE THREAD

**Issue by jaried** [TrentBrick/RewardConditionedUDRL#2]
When I run trainer.py, I get the following error, how can I fix it:

```
Traceback (most recent call last):
  File "D:\Program Files\JetBrains\PyCharm Community Edition 2021.2.2\plugins\python-ce\helpers\pydev\pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\Program Files\JetBrains\PyCharm Community Edition 2021.2.2\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/Tony/Documents/yunpan/invest/2022/quant/gym/URDL/RewardConditionedUDRL-main/trainer.py", line 362, in <module>
    main(args)
  File "D:/Tony/Documents/yunpan/invest/2022/quant/gym/URDL/RewardConditionedUDRL-main/trainer.py", line 316, in main
    run_lightning(config)
  File "D:/Tony/Documents/yunpan/invest/2022/quant/gym/URDL/RewardConditionedUDRL-main/trainer.py", line 249, in run_lightning
    model = LightningTemplate(game_dir, config, train_buffer, test_buffer)
  File "D:\Tony\Documents\yunpan\invest\2022\quant\gym\URDL\RewardConditionedUDRL-main\lightning_trainer.py", line 28, in __init__
    self.hparams = hparams
  File "D:\Anaconda3\envs\udrl\lib\site-packages\torch\nn\modules\module.py", line 1225, in __setattr__
    object.__setattr__(self, name, value)
AttributeError: can't set attribute
```

**Comment by TrentBrick** [comment]
Sorry for the slow reply. From this error alone I can't figure out what is going wrong. Have you figured it out yet? Could it be a version control problem?

**Comment by TrentBrick** [comment]
I am going to close this for now but happy to re-open it if you are still having problems!
